#!/bin/bash

#PBS -N FindWaldo
#PBS -q normal
#PBS -l select=1:ncpus=10:mem=40G
#PBS -l walltime=99:00:00
#PBS -P Personal
#PBS -j oe
#PBS -o ./output/find_waldo.o
#PBS -e ./output/find_waldo.e
# mail alert at (b)eginning, (e)nd and (a)bortion of execution
#PBS -m bea
# send mail to the following address
#PBS -M e0010911@u.nus.edu

echo find_waldo
pwd
cd $PBS_O_WORKDIR
module load anaconda/3
source activate cs4243
export PYTHONHOME=${HOME}/.conda/envs/cs4243
python find_waldo.py
